version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - DB_HOST=laravel_db
      - DB_PORT=3306
      - DB_DATABASE=system-inventory
      - DB_USERNAME=root
      - DB_PASSWORD=root

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: laravel_db
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
